### ISSUE TITLE
Missing first command parameter when using hx

### ISSUE THREAD

**Issue by thw1021** [jerabaul29/my_bash_scripts#2]
@jerabaul29 
I recently got a strange error when using `hx` command.
![Screenshot from 2020-09-23 14-03-11](https://user-images.githubusercontent.com/17957650/93972980-021bdb80-fda6-11ea-8a61-a5255210ac8c.png)
As you can see in the figure, when I execute `hx 15`, the first parameter `vi` is missing. But for other commands in history list with two numbers in the beginning, for example the first, there is no problem if I execute `hx 1`.

**Comment by jerabaul29** [comment]
Should be fixed with this:

https://github.com/jerabaul29/my_bash_scripts/commit/be814404032af994a324e76b71fa5edb8e845762

Can you update with the changes and confirm that it works? :)

**Comment by thw1021** [comment]
Yes, thank you.😁
